import Link from "next/link";
const swot={Strengths:["Distinct emotional-fitness category","Voice lowers journaling friction","Somatic inquiry + IFS creates method depth","Can complement coaches and therapists"],Weaknesses:["Current domain returns a public 404","High trust burden for intimate data","Value can feel abstract before first session","Safety boundaries require exceptional clarity"],Opportunities:["Daily or weekly emotional reps","Practitioner referral ecosystem","Private progress patterns over time","Cohort labs and guided programs"],Threats:["AI therapy confusion and regulatory scrutiny","General assistants copying the surface experience","Privacy concern suppressing activation","Poor sessions can damage trust quickly"]};
export default function Thyself(){return <main className="thyPage">
  <nav className="pocNav"><Link href="/">← Concept Lab</Link><b>THYSELF / POC 01</b><a href="#swot">SWOT</a></nav>
  <section className="thyHero"><div><p className="tag">Your emotional fitness practice</p><h1>Meet what’s<br/>alive in you.</h1><p className="lead">A private voice-guided space to notice what your body knows, untangle inner conflict, and build the capacity to hold yourself.</p><div className="actions"><a className="pill dark" href="#session">Begin a 10-minute session</a><a className="plain" href="#how">See how it works ↓</a></div><small>Not therapy. Not diagnosis. A practice for self-inquiry.</small></div><div className="orb"><span>Breathe in</span><i>4:00</i><b>Listening</b></div></section>
  <section className="proof" id="how"><p>EMOTIONAL WORK, MADE PRACTICABLE</p><div><h2>Notice.</h2><span>Follow physical sensation instead of explaining it away.</span></div><div><h2>Unblend.</h2><span>Meet the parts of you in conflict without forcing an answer.</span></div><div><h2>Integrate.</h2><span>Leave with one grounded reflection and a next practice.</span></div></section>
  <section className="session" id="session"><div><p className="tag">Session preview</p><h2>No blank page.<br/>Just your voice.</h2><p>The guide starts gently, listens without judgment, and adapts its questions to the sensations and parts you name.</p></div><div className="phone"><span>THYSELF</span><i className="pulse"/><p>“Where do you notice that<br/>in your body?”</p><button>Hold to speak</button></div></section>
  <section className="swot" id="swot"><header><p className="tag">Strategic report</p><h2>Thyself SWOT</h2><p>Evidence base: the live domain currently returns 404; a 2024 independent case study describes Thyself as voice AI using somatic inquiry and IFS, positioned as an “emotional gym,” not a therapist.</p></header><div className="swotGrid">{Object.entries(swot).map(([k,v])=><article key={k}><h3>{k}</h3><ul>{v.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>
  <section className="roadmap"><p className="tag">90-day proof plan</p><div><b>01</b><h3>Restore trust</h3><p>Re-establish the domain, publish clear privacy/safety language, and show the method before asking for a session.</p></div><div><b>02</b><h3>Prove the first session</h3><p>Measure start rate, completion, felt usefulness, and whether users return within seven days.</p></div><div><b>03</b><h3>Prove the habit</h3><p>Test weekly check-ins, personal pattern summaries, and practitioner referrals without over-medicalizing the product.</p></div></section>
  <footer className="source"><a href="https://www.moremyself.xyz/p/thyself" target="_blank" rel="noreferrer">Independent Thyself case study ↗</a><span>Concept—not medical advice or a production claim.</span></footer>
</main>}
