import Link from "next/link";
const swot={Strengths:["Concrete 10–15 minute promise","Voice removes typing friction","Zero-cost entry reduces resistance","Structured 26-question intake differentiates from open chat"],Weaknesses:["Current page appears intake-first, with limited context","Outcome quality is not previewed before commitment","Generic business-advice category is crowded","No visible proof or credibility layer in indexed copy"],Opportunities:["Instant blueprint preview before full intake","Founder, nonprofit, and side-hustle variants","Exportable one-page plan and action sprint","Natural bridge into services or software setup"],Threats:["ChatGPT can imitate generic discovery questions","Users may abandon a 26-question flow","Weak outputs undermine the entire promise","Free offer may attract low-intent demand"]};
export default function Blueprint(){return <main className="bpPage">
  <nav className="pocNav"><Link href="/">← Concept Lab</Link><b>BLUEPRINT / POC 02</b><a href="#swot">SWOT</a></nav>
  <section className="bpHero"><div><p className="tag">From idea fog to a plan you can use</p><h1>Say it out loud.<br/><em>Leave with the blueprint.</em></h1><p className="lead">A voice-guided founder session that turns your raw business idea into a clear customer, offer, launch plan, and next three moves.</p><div className="actions"><a className="pill blue" href="#demo">Start free · 10–15 min</a><a className="plain" href="#output">Preview your result ↓</a></div><small>26 guided questions · No typing · Zero cost</small></div><div className="blueprintSheet"><span>YOUR BLUEPRINT</span><h2>Neighborhood food studio</h2><ul><li><b>Customer</b> Busy families within 3 miles</li><li><b>Offer</b> Sunday prep packs</li><li><b>Proof</b> 10 paid pilot orders</li><li><b>Next move</b> Invite 25 neighbors</li></ul><i>READY TO TEST</i></div></section>
  <section className="outcomes" id="output"><p className="tag">Not another chatbot transcript</p><h2>One conversation.<br/>Five usable decisions.</h2><div>{["Who it is for","What you sell","Why they care","How to test it","What to do next"].map((x,i)=><article key={x}><span>0{i+1}</span><b>{x}</b></article>)}</div></section>
  <section className="demo" id="demo"><div><p className="tag">Question 07 of 26</p><h2>Who feels this problem most sharply?</h2><p>Don’t describe everyone. Tell me about the person already looking for a solution.</p></div><div className="wave"><i/><i/><i/><i/><i/><i/><i/><i/><button>Speak your answer</button></div></section>
  <section className="swot bpSwot" id="swot"><header><p className="tag">Strategic report</p><h2>Blueprint Chat SWOT</h2><p>Evidence base: the indexed live page promises a voice-guided, 26-question, 10–15 minute, zero-cost session with no typing. The concept below sharpens the missing outcome preview and proof story.</p></header><div className="swotGrid">{Object.entries(swot).map(([k,v])=><article key={k}><h3>{k}</h3><ul>{v.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></section>
  <section className="roadmap"><p className="tag">90-day proof plan</p><div><b>01</b><h3>Prove comprehension</h3><p>Test whether visitors can explain the output after five seconds. Put the blueprint preview before the intake.</p></div><div><b>02</b><h3>Prove completion</h3><p>Track start-to-finish rate by question and add save/resume plus visible progress.</p></div><div><b>03</b><h3>Prove action</h3><p>Measure whether users complete one recommended move within seven days—not merely whether they like the report.</p></div></section>
  <footer className="source"><a href="https://blueprintchat.xyz/" target="_blank" rel="noreferrer">Current Blueprint Chat ↗</a><span>Proof-of-concept strategy, not a production claim.</span></footer>
</main>}
